### ISSUE TITLE
Generated DbContext calls unknown method optionsBuilder.UseLazyLoadingProxies()

### ISSUE THREAD

**Issue by softevolution** [msawczyn/EFDesigner#269]
After updating to a recent version (currently v3.0.3.2) the generated DbContext includes a call to optionsBuilder.UseLazyLoadingProxies(). Since that I can't compile my solution any more. The error given is 

'DbContextOptionsBuilder' does not contain a definition for 'UseLazyLoadingProxies' and no accessible extension method 'UseLazyLoadingProxies' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)

I'm still use Entity Framework core 3.1.4 and have set the property 'Entity Framework Package Version' accordingly.

Can someone help me to fix this?

**Comment by msawczyn** [comment]
Duplicate of #266

**Comment by msawczyn** [comment]
Could you give 3.0.4 RC1 (available at https://github.com/msawczyn/EFDesigner/blob/master/dist/Sawczyn.EFDesigner.EFModel.DslPackage.vsix) a try? I believe this problem is now resolved.

**Comment by softevolution** [comment]
Sorry, not at the moment - I need to get a project production ready :(

**Comment by softevolution** [comment]
Sorry for the late reply. I've updated to v3.0.4.7 and the generated code is still not compatible with EF core 3.1.

It still generates optionsBuilder.UseLazyLoadingProxies(); and other things like

modelBuilder.Entity<global::DB.Person>().Navigation(e => e.Customer).IsRequired();

that EF core 3.1 doesn't know about. 

How can I install / get older versions? I'm stuck right know and get work with efdesigner and with my project :(

**Comment by msawczyn** [comment]
Have you overridden (i.e., included modified versions of) the ttinclude templates in your project?

**Comment by softevolution** [comment]
I don't have a .ttinclude in my project. 

Just some more info:

I have a separate project for the db entities which is a netstandard2.0 project. I include that library into my main project of type netcoreapp3.1.

I have this package ref in my (SDK style) project:

`<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.8" />`

My .efmodel file starts like this:

```
<?xml version="1.0" encoding="utf-8"?>
<modelRoot xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="3.0.4.7" Id="cba47279-0950-4257-bb2c-e4d5e72a52a4" entityContainerName="MainContext" namespace="DB" automaticMigrationsEnabled="false" entityOutputDirectory="Generated\Entities" contextOutputDirectory="Generated\Context" enumOutputDirectory="Generated\Enums" connectionStringName="DefaultConnection" showCascadeDeletes="false" databaseType="None" warnOnMissingDocumentation="false" entityFrameworkPackageVersion="3.1.8" structOutputDirectory="Generated\Structs" exposeForeignKeys="false" propertyAccessModeDefault="Field" generateDbContextFactory="false" showInterfaceIndicators="false" xmlns="http://schemas.microsoft.com/dsltools/EFModel">
  <classes>
```

Let me know if there's anything more that might help.

**Comment by softevolution** [comment]
I've now tried to update my project to net5 and I still get the compiler error about the unknown UseLazyLoadingProxies() function after code generation. Am I looking for the wrong error and something else is missing?

This is where the problem happens:

```
      /// <inheritdoc />
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
         optionsBuilder.UseLazyLoadingProxies();

         CustomInit(optionsBuilder);
      }
```
The error:

`MainContext.generated.cs(69,25,69,46): error CS1061: 'DbContextOptionsBuilder' does not contain a definition for 'UseLazyLoadingProxies' and no accessible extension method 'UseLazyLoadingProxies' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)`

Do you have an idea what reference might be missing?

**Comment by softevolution** [comment]
Ok, I solved the problem running under net5: I had to add include the nuget package Microsoft.EntityFrameworkCore.Proxies.

**Comment by msawczyn** [comment]
Glad to hear you've resolved this. My apologies for the lack of response - I've been ill for the past few weeks and haven't been able to sit in front of a computer. Should this issue be closed or do you need anything else?

**Comment by IoTFier** [comment]
Hi @msawczyn, are you alright ? Hope you are getting better.
@softevolution - thank you for your solution. It helped me even under .Net Standard 2.1
